### ISSUE TITLE
"Search in file(s)": Display directories first?

### ISSUE THREAD

**Issue by vemv** [emacsorphanage/helm-ag#313]
Hey there,

enjoying this library and hacking on it!

This is how `*Helm file completions*` looks like for me:

![image](https://user-images.githubusercontent.com/1162994/34596484-5b9cc0ea-f1e0-11e7-829e-8f5701344116.png)

Directories (in yellow) are sorted just like files (in white). I'd like that directories are displayed first, files second. Do you know if it's possible?

It'd probably be a good default.

Not sure if the issue belongs here or in https://github.com/emacs-helm/helm

Cheers - Victor

**Comment by jcs090218** [comment]
Sorry for the late reply!

I am the current maintainer of this package and this package is no longer further develop. If you would like this feature to be implement, feel free to make PR then I can merge it! Thanks! 😄
