### ISSUE TITLE
helm-do-ag does not respect helm-ag-use-grep-ignore-list

### ISSUE THREAD

**Issue by syl20bnr** [emacsorphanage/helm-ag#317]
Related to https://github.com/syl20bnr/spacemacs/issues/8299

We use `helm-do-ag` to integrate it with various other command line tools like pt, rg etc...
Seems that `helm-do-ag` does not honor `helm-ag-use-grep-ignore-list` whereas `helm-ag` does.

Is that expected ?

**Comment by xqliu** [comment]
Dear, Is there any estimation when this issue will be resolved?

Thanks

**Comment by CarlosMChica** [comment]
I have the same problem, is this going to be fixed?

Thanks in advance

**Comment by opsnull** [comment]
same problem here.

**Comment by jcs090218** [comment]
Thanks for concern this issue. I am the current maintainer of this project yet the project is **NOT** going to further develop. If anyone who are interested further develop this package, please make the PR and I will be reviewing it! Thanks! :)

**Comment by jcs090218** [comment]
Close this issue now, refer to #349.
