### ISSUE TITLE
Breaking change from 2017* to 2020* version

### ISSUE THREAD

**Issue by vemv** [emacsorphanage/helm-ag#345]
Hi, I've used `helm-ag-20170209.1545` for a long time. I guess it didn't get updated for a few years.

Now as I install a fresh machine, a 2020* version (or alternatively: 0.59, if using melpa-stable) gets installed.

Which causes the following error:

```
helm-do-ag: Wrong number of arguments: ((t) nil "Adds a :prompt option" (let ((search-dir (if (not (helm-ag--windows-p)) helm-ag--default-directory (if (helm-do-ag--target-one-directory-p helm-ag--default-target) (car helm-ag--default-target) helm-ag--default-directory)))) (helm-attrset (quote name) (helm-ag--helm-header search-dir) helm-source-do-ag) (helm :sources (quote (helm-source-do-ag)) :buffer "*helm-ag*" :keymap helm-do-ag-map :input (or (helm-ag--marked-input t) (helm-ag--insert-thing-at-point helm-ag-insert-at-point)) :history ...))), 1
```

The error might be simple enough to not particularly need further details - I guess some `defun` signature changed?

In any case, I'd kindly remind that breaking API changes tend to be a rather unpleasant thing to encounter. Most of the packages I install can last multiple years untouched.

Thanks - V

**Comment by syohex** [comment]
I suppose you use old byte-compiled file. Could you retry after remove all `*.elc` files ?

**Comment by vemv** [comment]
Thanks for the response,

I tried again after a `git clean -fdx` for removing all .el + .elc files. Unfortunately it didn't make a difference.

**Comment by syohex** [comment]
Did you remove **all** `.elc` files not only `helm-ag` ? I suppose your message is related to `helm` package which is dependency of `helm-ag`. So it is not enough to remove only `helm-ag` elc files that you should remove **all** elc files.

**Comment by vemv** [comment]
Yes, I had.

(Sorry, forgot to reply with that)

The nature of the issue is not .elc files, it's breaking API changes. If you do not wish to undo, them that's kinda OK for me, as it's a usual procedure for me to fork, then submodule.

**Comment by jcs090218** [comment]
@vemv So I assume that we are able to close this? Thanks!
