### ISSUE TITLE
 helm-ag--up-one-level does not work any longer

### ISSUE THREAD

**Issue by mikloq** [emacsorphanage/helm-ag#354]
- Emacs version: 26.3
- Operating system : Arch
- Search command(ag, pt, ack etc) and version: ripgrep 11.0.1

I recently updated my spacemacs to latest elpa and noticed that project search does not work as expected.

I use helm-project-do-rg , and when searching in git submodule I do (C-l) to search also in parent git repo, which changes recursively search path up the directory hierarchy. This unfortunately stopped working after update. Since I use this feature a lot I took a look why it stopped working.  I assume (C-l) is helm-ag--up-one-level and that does not work any longer.

Doing git bisect I found that 29d633643d1bb324a7c578aafa2b9caac3070043 breaks for me the (C-l) functionality and reverting it fixes the issue.

**Comment by jcs090218** [comment]
Refer to #346. (Just making note)

**Comment by jcs090218** [comment]
See #355.
