### ISSUE TITLE
Searches file names in a project using ag -g <pattern> is broken

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [emacsorphanage/helm-ag#357]
- Emacs version: GNU Emacs 26.3
- Operating system: Manjaro Linux
- Search command(ag, pt, ack etc) and version: ag version 2.2.0
- Last value of `helm-ag--last-command`

### Actual behavior

When searching for file names in a Git project with `M-s f` (see my config below) after entering a pattern to search, the list of matched file names is not showed. Instead `Search at <project path>` is showed

### Expected behavior

Before recent changes to help-ag code base, the `M-s f` (see my config below) triggered file name search and showed a list of files whose names matched the introduced pattern using the `ag -g <pattern>`

### Steps to reproduce

Type `M-s f` and start entering pattern to search for file names

My helm-ag configuration

```elisp
;; Helm Ag mode
(add-to-list 'load-path "~/.emacs.d/emacs-helm-ag")
(require 'helm-ag)
(custom-set-variables
    '(helm-ag-base-command "ag --nocolor --nogroup")
    '(helm-ag-command-option "--hidden --follow"))
(global-set-key (kbd "M-s s") 'helm-do-ag-project-root)

(defun helm-do-ag-project-root-search-file-names ()
    "Searches file names in a project using ag -g <pattern> command line tool"
    (interactive)
    (let ((helm-ag-command-option (concat helm-ag-command-option " -g")))
        (helm-do-ag-project-root)))
(global-set-key (kbd "M-s f") 'helm-do-ag-project-root-search-file-names)
```

**Comment by jcs090218** [comment]
See, #358.

Can you check if this PR solved your issue? Thanks! :)

**Comment by volodymyrprokopyuk** [comment]
Fantastic! The above PR solved the issue. Now file name search works fine! Thank you very much!

**Comment by volodymyrprokopyuk** [comment]
Hi @AtomicNess123 I'm not an expert of Elisp. If you just need a working out-of-the-box Emacs setup including searching files in specific directories consider [Doom Emacs](https://github.com/doomemacs/doomemacs).
