### ISSUE TITLE
Grouping output by file (showing filename for same hits just once)

### ISSUE THREAD

**Issue by iburunat** [emacsorphanage/helm-ag#359]
Is there a way to enable grouping for results? This way the name of the file would be mentioned only above the many hits below (having each hit its corresponding page number).

**Comment by syohex** [comment]
Sorry there is no way. It looks helm-rg supports grouping output. Please check it.

https://github.com/cosmicexplorer/helm-rg

**Comment by iburunat** [comment]
I suppose there is no plan or easy implementation for the future. Thanks for the prompt response!

**Comment by jcs090218** [comment]
I don't know if this is possible/impossible thing to be implemented! But if you like to have this feature, feel free to make PR! 😄 Just forgot the brought up about this! 👍 And of course you can leave this issue open if you want!
