### ISSUE TITLE
How to highlight helm-ag result in buffers opened by the follow-mode?

### ISSUE THREAD

**Issue by taquangtrung** [emacsorphanage/helm-ag#360]
- Emacs version: 26.3
- Operating system: Linux Mint 19.2
- Search command: ag, version 2.1.0
- Last value of `helm-ag--last-command`

```
("ag" "--nocolor" "--nogroup" "--ignore=.#*" "--ignore=*.cmxs" "--ignore=*.cmti"
"--ignore=*.cmt" "--ignore=*.annot" "--ignore=*.cmi" "--ignore=*.cmxa" "--ignore=*.cma" "--ignore=*.cmx" "--ignore=*.cmo" "--ignore=*.pho" "--ignore=*.phi" "--ignore=*.glob" "--ignore=*.vo" "--ignore=*.hi" "--ignore=*.o" "--ignore=*~" "--ignore=*.bin" "--ignore=*.lbin" "--ignore=*.so"
"--ignore=*.a" "--ignore=*.ln" "--ignore=*.blg" "--ignore=*.bbl" "--ignore=*.elc" "--ignore=*.lof" "--ignore=*.glo" "--ignore=*.idx" "--ignore=*.lot" "--ignore=*.fmt" "--ignore=*.tfm" "--ignore=*.class"
"--ignore=*.fas" "--ignore=*.lib" "--ignore=*.mem" "--ignore=*.x86f" "--ignore=*.sparcf" "--ignore=*.dfsl" "--ignore=*.pfsl" "--ignore=*.d64fsl" "--ignore=*.p64fsl" "--ignore=*.lx64fsl" "--ignore=*.lx32fsl" "--ignore=*.dx64fsl" "--ignore=*.dx32fsl" "--ignore=*.fx64fsl"
"--ignore=*.fx32fsl" "--ignore=*.sx64fsl" "--ignore=*.sx32fsl" "--ignore=*.wx64fsl" "--ignore=*.wx32fsl" "--ignore=*.fasl" "--ignore=*.ufsl" "--ignore=*.fsl" "--ignore=*.dxl" "--ignore=*.lo" "--ignore=*.la"
"--ignore=*.gmo" "--ignore=*.mo" "--ignore=*.toc" "--ignore=*.aux" "--ignore=*.cp" "--ignore=*.fn" "--ignore=*.ky" "--ignore=*.pg" "--ignore=*.tp" "--ignore=*.vr" "--ignore=*.cps" "--ignore=*.fns" "--ignore=*.kys" "--ignore=*.pgs" "--ignore=*.tps" "--ignore=*.vrs" "--ignore=*.pyc" "--ignore=*.pyo" "--ignore=SCCS" "--ignore=RCS" "--ignore=CVS" "--ignore=MCVS" "--ignore=.src" "--ignore=.svn" "--ignore=.git" "--ignore=.hg" "--ignore=.bzr" "--ignore=_MTN" "--ignore=_darcs" "--ignore={arch}"
"module")
```

### Actual behavior

When the follow-mode is enabled, helm-ag results are not highlighted in buffers opened by the follow-mode.

When I tested with both Spacemacs and the vanilla Emacs with only `helm-ag` installed, the same behavior occurs. 

Here is the screenshot in my vanilla Emacs. The matched string `module` in the buffer `proof_nonentail.ml` is not highlighted.

![helm-ag](https://user-images.githubusercontent.com/193967/83112256-77c5b280-a0f8-11ea-95d9-d9240dbdcadf.png)

### Expected behavior

It would be nice if helm-ag results are also highlighted in each buffer opened by the follow-mode. I saw that previously, this behavior is possible, such as the screenshot in this issue.

https://github.com/emacsorphanage/helm-ag/issues/209

### Steps to reproduce

Use `helm-do-ag` command and use `C-c C-f` to enable the follow-mode

**Comment by syohex** [comment]
Do you install any Ocaml packages ? Emacs does not support Ocaml(or similar ML language) and opens `.ml` file with `lisp-mode` by default. Please install ocaml packages via package manager and try again. `auto-mode-alist` has following value if you configura Ocaml language correctly.

```lisp
("\\.ml[ip]?\\'" . tuareg-mode)
```

You can test manually with following configuration too.

```lisp
(add-to-list 'auto-mode-alist '("\\.ml[ip]?\\'" . tuareg-mode))
```

**Comment by taquangtrung** [comment]
Thanks for the reply. The problem still occurs when `tuareg-mode` is enabled.

Here is the screenshot in my vanilla Emacs. I also encounter the same issue in Spacemacs.

![helm-ag2](https://user-images.githubusercontent.com/193967/83118208-a6e02200-a100-11ea-8a96-871aac41ea8f.png)

**Comment by syohex** [comment]
Sorry I misunderstood.

**Comment by syohex** [comment]
I suppose your expected feature does not implement neither helm-ag nor helm, however launching `isearch-forward` or similar commands(or `Ctrl-s` or `Ctrl-r`) before inputting narrowing keyword word highlights buffers which is opened by `helm-follow-mode`.

1. `M-x helm-ag`
1. Input some query
1. Enable follow mode by `Ctrl-c Ctrl-f`
1. `Ctrl-s`
1. Input `module`
1. then highlight module in buffer

**Comment by taquangtrung** [comment]
I followed your previous tutorial, but at step 4, `C-s` is not defined.

Somehow this feature appeared in the latter part of this GIF screenshot of yours, posting in this issue https://github.com/emacsorphanage/helm-ag/issues/209.

![helm-ag](https://cloud.githubusercontent.com/assets/554281/12407453/d59f246c-be9a-11e5-9d34-b7cc87bbfffa.gif)

I also see a similar feature in helm-grep.

**Comment by syohex** [comment]
Ah, I understand its feature. I'll send PR later, please wait for a while.

**Comment by taquangtrung** [comment]
Great! Thanks a lot for your quick responses.

**Comment by syohex** [comment]
See #361

**Comment by syohex** [comment]
#361 has been merged. Please check latest version

**Comment by jcs090218** [comment]
@syohex Thanks again! :) 

@taquangtrung Can you check if this feature is resolved? Thanks! 😄

**Comment by taquangtrung** [comment]
@syohex Many thanks for the update. I'm impressed with the fix in lighting speed.

@jcs090218 Yes, it works perfectly fine.

**Comment by jcs090218** [comment]
Close this issue now! :)
