### ISSUE TITLE
Specifying extra command line option of ag with minus prefix(M-- or C--)

### ISSUE THREAD

**Issue by Gahamelas** [emacsorphanage/helm-ag#364]
Hi, 

I did not totally understand what it means to specify extra command line option with M-- or C-- Could you provide an example? 

```
helm-do-ag
Search with ag like helm-do-grep-ag , helm-grep-do-git-grep. You can specify extra command line option of ag with minus prefix(M-- or C--).
```

**Comment by syohex** [comment]
![example](https://user-images.githubusercontent.com/554281/89899155-d0e3b380-dc1c-11ea-87be-3e3bddb48754.gif)

You can use it and pass `-G\.md` extra option for searching some specified files like markdown files as above. However it looks this feature has bug which does not clear extra argument. I have sent its PR #365

**Comment by jcs090218** [comment]
Merged! I appreciated! 👍 

@Gahamelas Can you please check if this patch resolved your issue? Thanks! 😄

**Comment by Gahamelas** [comment]
Thank you @syohex and @jcs090218 . Working good so far!
