### ISSUE TITLE
Lisp error: (void-variable default-input)

### ISSUE THREAD

**Issue by jsobiecki** [emacsorphanage/helm-ag#368]
- Emacs version: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)
 of 2020-03-26, modified by Debian
- GNU\Linux (Ubuntu 20.4)
- Search command(ag, pt, ack etc) and version: ag 2.2.0
- Last value of `helm-ag--last-command`

### Actual behavior 
After last package update, extension stopped to work. At each attempt of work, I getting "void-variable default-input. error:

Debugger entered--Lisp error: (void-variable default-input)
  helm-do-ag("~/workspace/project" nil nil)
  helm-do-ag-project-root()
  funcall-interactively(helm-do-ag-project-root)
  call-interactively(helm-do-ag-project-root nil nil)
  command-execute(helm-do-ag-project-root)

### Expected behavior

It should allow me to refine my search conditions in minibuffer, but I don't have chance to do so.

### Steps to reproduce

Usage of helm-do-ag-project-root function

**Comment by syohex** [comment]
I suppose merging #343 broke code. It should be reverted and its change should be applied to latest code base.

**Comment by jcs090218** [comment]
I have reverted to version `0.62` for now.

**Comment by jsobiecki** [comment]
Hi guys, thanks for feedback. I'll also try to revert to 0.62

**Comment by jcs090218** [comment]
Sorry for the inconvenient! I guess PR #343 will not be merged from the current state.

@kiennq Do you want to redo the PR? I suppose this should be a simple fix and we just need to make sure it doesn't break this time!

Thanks everyone! 😖

**Comment by jcs090218** [comment]
Close this issue for now. This is cause by a feature PR, #343.
