### ISSUE TITLE
setting default search directory

### ISSUE THREAD

**Issue by Kejia** [emacsorphanage/helm-ag#373]
i bind `C-c s` to `helm-do-ag`, and every time it asks me to choose the search dir. i would like that i can set some global variable that can direct `helm-do-ag` to search in that dir.
 
thank you for your work.

**Comment by syohex** [comment]
You can control search target by 1st argument of `helm-do-ag`

```lisp
(defun my/helm-do-ag ()
  (interactive)
  (helm-do-ag your-search-directory))
```

For example, you define as bellow if you always want to search under current directory

```lisp
(defun my/helm-do-ag ()
  (interactive)
  (helm-do-ag default-directory))
```

Or some specific directory

```lisp
(defun my/helm-do-ag ()
  (interactive)
  (helm-do-ag "/usr/src/linux"))
```

**Comment by jcs090218** [comment]
Yeah, I think @syohex gives the best solution here! 👍

**Comment by Kejia** [comment]
thank you for your code fragment. i apply the following one to my key-binding:
```lisp
(defun my/helm-do-ag ()
  (interactive)
  (let ((helm-ag-work-dir (if (boundp 'helm-ag-work-dir)
															helm-ag-work-dir
														default-directory)))
		(helm-do-ag helm-ag-work-dir)))
```
it works well.

**Comment by jcs090218** [comment]
I guess this issue can be closed? Feel free to reopen this if you find out useful! Thanks! 😄
