### ISSUE TITLE
helm-ag-edit

### ISSUE THREAD

**Issue by JocelynDelalande** [emacsorphanage/helm-ag#376]
- Emacs version 26
- Operating system Debian buster
- Search command(ag, pt, ack etc) and version ag 2.2.0

### Actual behavior

- interface hangs for minutes 

### Expected behavior

- it takes a couple of seconds

### Steps to reproduce

- search
- edit helm-ag search buffer (C-c C-e) a large search (ex: ~100 files)
- save

### Discussion

I guess the cause is files are opened for editing, each of them in a buffer, triggering various hooks that may be configured. For example in my case it seems to loads python-mode that itself has a hook configured to load on importmagic-mode, which is costly to run.

**Comment by syohex** [comment]
Do you use latest version ? I suppose #339 fixed such issue.

**Comment by JocelynDelalande** [comment]
@syohex I can confirm that it got fixed in recent version 
yesterday (helm-ag v0.54), I (literally) had time to cook my dinner while saving a change from helm-ag, but today, the same edit with helm-ag v0.64 got saved in 3 seconds \o/

I now have to find other strategies to make sure I eat something for dinner ;-).

A big thanks for that tool and kudos also to @Namburgesas for the fix
