### ISSUE TITLE
[Question] Is there any way helm-ag specify the files in “pattern:” prompt?

### ISSUE THREAD

**Issue by yamatakau08** [emacsorphanage/helm-ag#382]
Is there any way helm-ag specify the files in “pattern:” prompt?
I want to search pattern in the files e.g log1 log2.

**Comment by syohex** [comment]
I suppose there is no way. You can use `helm-do-ag` for that purpose. (Mark files by Ctrl-space and search)

**Comment by yamatakau08** [comment]
Thank you for introducing `helm-do-ag`
I could archive what I wanted.
