### ISSUE TITLE
How the `helm-do-ag` preview the file through the helm framework? (question)

### ISSUE THREAD

**Issue by ccqpein** [emacsorphanage/helm-ag#410]
Everything is fine. I am trying to write my emacs mode using the helm framework and it actually do very similar thing as helm-ag. 

I am studying the `helm-ag` source code. It takes me some time to write an async demo by using the helm and I eventually get the candidates done. Then I notice after I do the `helm-do-ag`, when I selected the different candidates, my main window will jump through the files and locate me to where the candidates are.

I added some messages in the source code and figured out every time the `helm-ag--persistent-action` will be called. However, my mode's class's `persistent-action`  only calls when I do `C-j` like the helm [doc](https://github.com/emacs-helm/helm/wiki/Developing#writing-persistent-actions) says. 

May I ask how you guys do it? How can I make my major window jump to the candidate location without `C-j`? 

Sorry, I don't know where to communicate with you guys so I left this question here. Thank you!

**Comment by jcs090218** [comment]
Are you talking about something like these? 🤔 

- https://github.com/emacsorphanage/helm-swoop
- https://github.com/jcs-legacy/helm-file-preview

**Comment by ccqpein** [comment]
@jcs090218 Thanks for your recommendations, it is helpful for me to learn helm. 

Besides, I find I don't set the `:follow` to `:follow (and helm-follow-mode-persistent 1)` in my source. `helm-ag` can jump between files by calling `persistent-action` because I set the `(helm-follow-mode-persistent t)` in my `emacs.d`.
